name: "雪鸮"
permalink: /:year/:month/:day/:title.html

author: "wavexu"
atom-baseurl: "https://wavexu.cn"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fas fa-list-ul
    href: /archive.html
  - title: Tags
    class: fas fa-tags
    href: /tags.html
  - title: About
    class: fas fa-user
    href: /about.html
  - title: Subscribe
    class: fas fa-rss
    href: /atom.xml
